// src/routes/comprehend/projects/+page.svelte
<script>
	// Mock data for demonstration
	const projects = [
		{
			id: '1',
			name: 'Tax Law Knowledge Base',
			description: 'Knowledge base for tax regulations and case studies',
			createdAt: '2024-02-23',
			status: 'Active'
		},
		{
			id: '2',
			name: 'Corporate Documentation',
			description: 'Internal documentation and procedures',
			createdAt: '2024-02-22',
			status: 'Processing'
		}
	];
</script>

<div class="py-6 px-4 sm:px-6 lg:px-8">
	<div class="max-w-7xl mx-auto">
		<div class="sm:flex sm:items-center">
			<div class="sm:flex-auto">
				<h1 class="text-3xl font-bold text-gray-900">Projects</h1>
				<p class="mt-2 text-sm text-gray-700">
					A list of all your Comprehend projects and their current status.
				</p>
			</div>
			<div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
				<button
					type="button"
					class="inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto"
				>
					Create Project
				</button>
			</div>
		</div>

		<div class="mt-8 overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
			<table class="min-w-full divide-y divide-gray-300">
				<thead class="bg-gray-50">
					<tr>
						<th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">
							Name
						</th>
						<th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
							Description
						</th>
						<th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
							Created
						</th>
						<th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
							Status
						</th>
						<th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
							<span class="sr-only">Actions</span>
						</th>
					</tr>
				</thead>
				<tbody class="divide-y divide-gray-200 bg-white">
					{#each projects as project}
						<tr>
							<td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
								<a href="/comprehend/projects/{project.id}/conversations" class="hover:text-indigo-600">
									{project.name}
								</a>
							</td>
							<td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{project.description}</td>
							<td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{project.createdAt}</td>
							<td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{project.status}</td>
							<td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
								<a href="/comprehend/projects/{project.id}/settings/general" class="text-indigo-600 hover:text-indigo-900">
									Settings
								</a>
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	</div>
</div>

// app/comprehend/projects/page.tsx
"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { ChevronRight } from "lucide-react";

// Mock data for demonstration
const mockProjects = [
  {
    id: "legal-research",
    name: "Legal Research Assistant",
    description: "AI-powered legal document analysis and research tool",
    documents: 156,
    lastUpdated: "2024-02-24",
  },
  {
    id: "medical-knowledge",
    name: "Medical Knowledge Base",
    description: "Comprehensive medical research and documentation system",
    documents: 324,
    lastUpdated: "2024-02-23",
  },
];

export default function ProjectsPage() {
  const router = useRouter();

  return (
    <div className="max-w-7xl mx-auto p-6">
      <div className="flex justify-between items-center mb-8">
        <h1 className="text-2xl font-semibold">Projects</h1>
        <Link
          href="/comprehend/projects/new"
          className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2"
        >
          Create Project
        </Link>
      </div>

      <div className="rounded-md border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-[300px]">Name</TableHead>
              <TableHead className="min-w-[300px]">Description</TableHead>
              <TableHead className="w-[150px] text-right">Documents</TableHead>
              <TableHead className="w-[150px]">Last Updated</TableHead>
              <TableHead className="w-[50px]"></TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {mockProjects.map((project) => (
              <TableRow
                key={project.id}
                className="cursor-pointer hover:bg-muted/50"
                onClick={() => router.push(`/comprehend/projects/${project.id}/dashboard`)}
              >
                <TableCell className="font-medium">{project.name}</TableCell>
                <TableCell className="text-muted-foreground">
                  {project.description}
                </TableCell>
                <TableCell className="text-right">{project.documents}</TableCell>
                <TableCell>{project.lastUpdated}</TableCell>
                <TableCell>
                  <ChevronRight className="h-4 w-4 ml-2" />
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      {mockProjects.length === 0 && (
        <div className="text-center py-12">
          <h3 className="text-lg font-semibold">No projects yet</h3>
          <p className="text-sm text-muted-foreground mt-1">
            Create your first project to get started
          </p>
        </div>
      )}
    </div>
  );
}
